name: LPEconomy
main: pl.lifelesspixels.lpeconomy.LPEconomy
version: 0.1
api-version: 1.19
depend: [LPUtilities, LPDataManager]
commands:
  balance:
    description: Used to check player's balance
    aliases: [bal]
  addbalance:
    description: Used to add balance for specified player
permissions:
  lpeconomy.command.balance.own:
    default: true
  lpeconomy.command.balance.others:
    default: op
  lpeconomy.command.addbalance:
    default: op